// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wnc.Data;

#nullable disable

namespace wnc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260321162810_AllowZeroTrainingProgramQuota")]
    partial class AllowZeroTrainingProgramQuota
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("wnc.Models.AdmissionApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("LastResubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewDeadlineAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoundProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SubmissionNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationCode")
                        .IsUnique();

                    b.HasIndex("RoundProgramId");

                    b.HasIndex("CandidateId", "RoundProgramId")
                        .IsUnique();

                    b.HasIndex("CurrentStatus", "SubmittedAt");

                    b.ToTable("admission_applications", null, t =>
                        {
                            t.HasCheckConstraint("ck_admission_applications_submission_number", "[SubmissionNumber] >= 0");
                        });
                });

            modelBuilder.Entity("wnc.Models.AdmissionMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MethodCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("MethodCode")
                        .IsUnique();

                    b.ToTable("admission_methods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Academic transcript based admission",
                            MethodCode = "HOC_BA",
                            MethodName = "Xet hoc ba",
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Exam score based admission",
                            MethodCode = "DIEM_THI",
                            MethodName = "Xet diem thi",
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("cccccccc-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Direct admission",
                            MethodCode = "TUYEN_THANG",
                            MethodName = "Xet tuyen thang",
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("wnc.Models.AdmissionRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AdmissionYear")
                        .HasColumnType("int");

                    b.Property<bool>("AllowEnrollmentConfirmation")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoundCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoundName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("RoundCode")
                        .IsUnique();

                    b.HasIndex("AdmissionYear", "Status", "StartAt", "EndAt");

                    b.ToTable("admission_rounds", null, t =>
                        {
                            t.HasCheckConstraint("ck_admission_rounds_time", "[StartAt] < [EndAt]");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbb1-1111-1111-1111-111111111111"),
                            AdmissionYear = 2025,
                            AllowEnrollmentConfirmation = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndAt = new DateTime(2025, 6, 30, 23, 59, 59, 0, DateTimeKind.Utc),
                            Notes = "Dot xet tuyen chinh quy nam 2025",
                            RoundCode = "DOT1-2025",
                            RoundName = "Dot 1 nam 2025",
                            StartAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "PUBLISHED",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa1-1111-1111-1111-111111111111"),
                            AdmissionYear = 2026,
                            AllowEnrollmentConfirmation = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndAt = new DateTime(2026, 6, 30, 23, 59, 59, 0, DateTimeKind.Utc),
                            Notes = "Dot xet tuyen chinh quy nam 2026",
                            RoundCode = "DOT1-2026",
                            RoundName = "Dot 1 nam 2026",
                            StartAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "PUBLISHED",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbbbbb2-1111-1111-1111-111111111111"),
                            AdmissionYear = 2026,
                            AllowEnrollmentConfirmation = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndAt = new DateTime(2026, 9, 30, 23, 59, 59, 0, DateTimeKind.Utc),
                            Notes = "Dot xet tuyen chinh quy dot 2 nam 2026",
                            RoundCode = "DOT2-2026",
                            RoundName = "Dot 2 nam 2026",
                            StartAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "PUBLISHED",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbbbbb3-1111-1111-1111-111111111111"),
                            AdmissionYear = 2027,
                            AllowEnrollmentConfirmation = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndAt = new DateTime(2027, 6, 30, 23, 59, 59, 0, DateTimeKind.Utc),
                            Notes = "Dot xet tuyen chinh quy nam 2027",
                            RoundCode = "DOT3-2027",
                            RoundName = "Dot 3 nam 2027",
                            StartAt = new DateTime(2027, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "PUBLISHED",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("wnc.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("PhoneVerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.HasIndex("Status");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("wnc.Models.ApplicationDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Checksum")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("UploadedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("UploadedBy");

                    b.HasIndex("ApplicationId", "DocumentTypeId", "IsLatest");

                    b.ToTable("application_documents", null, t =>
                        {
                            t.HasCheckConstraint("ck_application_documents_file_size", "[FileSize] >= 0");
                        });
                });

            modelBuilder.Entity("wnc.Models.ApplicationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("MajorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PriorityOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("MajorId");

                    b.HasIndex("MethodId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("ApplicationId", "PriorityOrder")
                        .IsUnique();

                    b.ToTable("application_preferences", null, t =>
                        {
                            t.HasCheckConstraint("ck_application_preferences_priority_order", "[PriorityOrder] > 0");
                        });
                });

            modelBuilder.Entity("wnc.Models.ApplicationReviewNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsVisibleToCandidate")
                        .HasColumnType("bit");

                    b.Property<string>("NoteType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("AuthorUserId");

                    b.ToTable("application_review_notes", (string)null);
                });

            modelBuilder.Entity("wnc.Models.ApplicationStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("InternalNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("ApplicationId", "ChangedAt");

                    b.ToTable("application_status_histories", (string)null);
                });

            modelBuilder.Entity("wnc.Models.ApplicationSupplementRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("RequestedBy");

                    b.ToTable("application_supplement_requests", (string)null);
                });

            modelBuilder.Entity("wnc.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NewData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldData")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("EntityName", "EntityId", "CreatedAt");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("wnc.Models.AuthLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("LoggedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("LoginIdentifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LoggedAt");

                    b.HasIndex("UserId");

                    b.ToTable("auth_logs", (string)null);
                });

            modelBuilder.Entity("wnc.Models.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("AvatarFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProvinceCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ward")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NationalId")
                        .IsUnique()
                        .HasFilter("[NationalId] IS NOT NULL");

                    b.HasIndex("ProvinceCode");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("candidates", (string)null);
                });

            modelBuilder.Entity("wnc.Models.CandidateEducationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcademicRank")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Gpa")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("GraduationYear")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("candidate_education_profiles", (string)null);
                });

            modelBuilder.Entity("wnc.Models.CandidatePriorityProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("EvidenceFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriorityCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PriorityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("ScoreValue")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("candidate_priority_profiles", (string)null);
                });

            modelBuilder.Entity("wnc.Models.DocumentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentCode")
                        .IsUnique();

                    b.ToTable("document_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Citizen identification card",
                            DocumentCode = "CCCD",
                            DocumentName = "Can cuoc cong dan",
                            Status = "ACTIVE"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Academic transcript",
                            DocumentCode = "HOC_BA",
                            DocumentName = "Hoc ba",
                            Status = "ACTIVE"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Birth certificate",
                            DocumentCode = "KHAI_SINH",
                            DocumentName = "Giay khai sinh",
                            Status = "ACTIVE"
                        });
                });

            modelBuilder.Entity("wnc.Models.EnrollmentConfirmation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConfirmationStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("ConfirmedByCandidateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("enrollment_confirmations", (string)null);
                });

            modelBuilder.Entity("wnc.Models.Major", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("MajorCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MajorName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quota")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("MajorCode")
                        .IsUnique();

                    b.HasIndex("ProgramId");

                    b.ToTable("majors", null, t =>
                        {
                            t.HasCheckConstraint("ck_majors_quota", "[Quota] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaa2-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cong nghe thong tin",
                            DisplayOrder = 1,
                            MajorCode = "CNTT",
                            MajorName = "Cong nghe thong tin",
                            ProgramId = new Guid("99999999-7777-7777-7777-777777777777"),
                            Quota = 150,
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa3-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ke toan doanh nghiep",
                            DisplayOrder = 2,
                            MajorCode = "KT",
                            MajorName = "Ke toan",
                            ProgramId = new Guid("99999999-7777-7777-7777-777777777777"),
                            Quota = 100,
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa4-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Marketing so",
                            DisplayOrder = 3,
                            MajorCode = "MK",
                            MajorName = "Marketing",
                            ProgramId = new Guid("99999999-7777-7777-7777-777777777777"),
                            Quota = 80,
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("wnc.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UserId", "Status", "CreatedAt");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("wnc.Models.NotificationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SubjectTemplate")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("TemplateCode")
                        .IsUnique();

                    b.ToTable("notification_templates", (string)null);
                });

            modelBuilder.Entity("wnc.Models.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("wnc.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "ADMIN",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "System administrator",
                            IsSystemRole = true,
                            Name = "Administrator",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "ADMISSION_OFFICER",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Admission operations staff",
                            IsSystemRole = true,
                            Name = "Admission Officer",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "REPORT_VIEWER",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read-only reporting role",
                            IsSystemRole = true,
                            Name = "Report Viewer",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Code = "CANDIDATE",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Candidate account role",
                            IsSystemRole = true,
                            Name = "Candidate",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("wnc.Models.RoundAdmissionMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CalculationRule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CombinationCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("MethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MinimumScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PriorityPolicy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoundProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("MethodId");

                    b.HasIndex("RoundProgramId");

                    b.ToTable("round_admission_methods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaa01-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MethodId = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            MinimumScore = 7.0m,
                            RoundProgramId = new Guid("aaaaaaa5-1111-1111-1111-111111111111"),
                            Status = "ACTIVE"
                        },
                        new
                        {
                            Id = new Guid("aaaaaa02-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MethodId = new Guid("bbbbbbbb-2222-2222-2222-222222222222"),
                            MinimumScore = 18.0m,
                            RoundProgramId = new Guid("aaaaaaa5-1111-1111-1111-111111111111"),
                            Status = "ACTIVE"
                        },
                        new
                        {
                            Id = new Guid("aaaaaa03-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MethodId = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            MinimumScore = 6.5m,
                            RoundProgramId = new Guid("aaaaaaa6-1111-1111-1111-111111111111"),
                            Status = "ACTIVE"
                        },
                        new
                        {
                            Id = new Guid("aaaaaa04-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MethodId = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            MinimumScore = 6.0m,
                            RoundProgramId = new Guid("aaaaaaa7-1111-1111-1111-111111111111"),
                            Status = "ACTIVE"
                        });
                });

            modelBuilder.Entity("wnc.Models.RoundDocumentRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("MaxFiles")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresNotarization")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresOriginalCopy")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoundProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("RoundProgramId", "DocumentTypeId")
                        .IsUnique();

                    b.ToTable("round_document_requirements", null, t =>
                        {
                            t.HasCheckConstraint("ck_round_document_requirements_max_files", "[MaxFiles] > 0");
                        });
                });

            modelBuilder.Entity("wnc.Models.RoundProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("MajorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PublishedQuota")
                        .HasColumnType("int");

                    b.Property<int>("Quota")
                        .HasColumnType("int");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("MajorId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("RoundId", "ProgramId", "MajorId")
                        .IsUnique();

                    b.ToTable("round_programs", null, t =>
                        {
                            t.HasCheckConstraint("ck_round_programs_published_quota", "[PublishedQuota] IS NULL OR [PublishedQuota] >= 0");

                            t.HasCheckConstraint("ck_round_programs_quota", "[Quota] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaa5-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MajorId = new Guid("aaaaaaa2-1111-1111-1111-111111111111"),
                            ProgramId = new Guid("99999999-7777-7777-7777-777777777777"),
                            PublishedQuota = 120,
                            Quota = 150,
                            RoundId = new Guid("aaaaaaa1-1111-1111-1111-111111111111"),
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa6-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MajorId = new Guid("aaaaaaa3-1111-1111-1111-111111111111"),
                            ProgramId = new Guid("99999999-7777-7777-7777-777777777777"),
                            PublishedQuota = 80,
                            Quota = 100,
                            RoundId = new Guid("aaaaaaa1-1111-1111-1111-111111111111"),
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa7-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MajorId = new Guid("aaaaaaa4-1111-1111-1111-111111111111"),
                            ProgramId = new Guid("99999999-7777-7777-7777-777777777777"),
                            PublishedQuota = 60,
                            Quota = 80,
                            RoundId = new Guid("aaaaaaa1-1111-1111-1111-111111111111"),
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbbbb01-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MajorId = new Guid("aaaaaaa2-1111-1111-1111-111111111111"),
                            ProgramId = new Guid("99999999-7777-7777-7777-777777777777"),
                            PublishedQuota = 90,
                            Quota = 100,
                            RoundId = new Guid("bbbbbbb1-1111-1111-1111-111111111111"),
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbbbb02-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MajorId = new Guid("aaaaaaa3-1111-1111-1111-111111111111"),
                            ProgramId = new Guid("99999999-7777-7777-7777-777777777777"),
                            PublishedQuota = 70,
                            Quota = 80,
                            RoundId = new Guid("bbbbbbb1-1111-1111-1111-111111111111"),
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbbbb03-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MajorId = new Guid("aaaaaaa2-1111-1111-1111-111111111111"),
                            ProgramId = new Guid("99999999-7777-7777-7777-777777777777"),
                            PublishedQuota = 80,
                            Quota = 100,
                            RoundId = new Guid("bbbbbbb2-1111-1111-1111-111111111111"),
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbbbb04-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MajorId = new Guid("aaaaaaa2-1111-1111-1111-111111111111"),
                            ProgramId = new Guid("99999999-7777-7777-7777-777777777777"),
                            PublishedQuota = 100,
                            Quota = 120,
                            RoundId = new Guid("bbbbbbb3-1111-1111-1111-111111111111"),
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("wnc.Models.SystemConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConfigKey")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.ToTable("system_configs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888881"),
                            ConfigKey = "AUTH.LOGIN_BY_EMAIL",
                            ConfigValue = "true",
                            Description = "Allow login by email",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888882"),
                            ConfigKey = "AUTH.LOGIN_BY_PHONE",
                            ConfigValue = "true",
                            Description = "Allow login by phone",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("wnc.Models.TrainingProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("DurationText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EducationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ManagingUnit")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProgramCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Quota")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("TuitionFee")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ProgramCode")
                        .IsUnique();

                    b.ToTable("training_programs", null, t =>
                        {
                            t.HasCheckConstraint("ck_training_programs_quota", "[Quota] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default seeded training program",
                            DisplayOrder = 1,
                            DurationText = "2.5 years",
                            EducationType = "CAO_DANG",
                            ManagingUnit = "Admissions Office",
                            ProgramCode = "CD_CHINH_QUY",
                            ProgramName = "Cao dang chinh quy",
                            Quota = 500,
                            Status = "ACTIVE",
                            TuitionFee = 12000000m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("wnc.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasFilter("[RevokedAt] IS NULL");

                    b.HasIndex("UserId", "RoleId", "RevokedAt");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("wnc.Models.AdmissionApplication", b =>
                {
                    b.HasOne("wnc.Models.Candidate", "Candidate")
                        .WithMany("AdmissionApplications")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("wnc.Models.RoundProgram", "RoundProgram")
                        .WithMany("AdmissionApplications")
                        .HasForeignKey("RoundProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("RoundProgram");
                });

            modelBuilder.Entity("wnc.Models.AdmissionRound", b =>
                {
                    b.HasOne("wnc.Models.AppUser", "CreatedByUser")
                        .WithMany("CreatedAdmissionRounds")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("wnc.Models.ApplicationDocument", b =>
                {
                    b.HasOne("wnc.Models.AdmissionApplication", "Application")
                        .WithMany("ApplicationDocuments")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wnc.Models.DocumentType", "DocumentType")
                        .WithMany("ApplicationDocuments")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("wnc.Models.AppUser", "UploadedByUser")
                        .WithMany("UploadedDocuments")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Application");

                    b.Navigation("DocumentType");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("wnc.Models.ApplicationPreference", b =>
                {
                    b.HasOne("wnc.Models.AdmissionApplication", "Application")
                        .WithMany("ApplicationPreferences")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wnc.Models.Major", "Major")
                        .WithMany("ApplicationPreferences")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("wnc.Models.AdmissionMethod", "Method")
                        .WithMany("ApplicationPreferences")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("wnc.Models.TrainingProgram", "Program")
                        .WithMany("ApplicationPreferences")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Major");

                    b.Navigation("Method");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("wnc.Models.ApplicationReviewNote", b =>
                {
                    b.HasOne("wnc.Models.AdmissionApplication", "Application")
                        .WithMany("ApplicationReviewNotes")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wnc.Models.AppUser", "AuthorUser")
                        .WithMany("ApplicationReviewNotes")
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("AuthorUser");
                });

            modelBuilder.Entity("wnc.Models.ApplicationStatusHistory", b =>
                {
                    b.HasOne("wnc.Models.AdmissionApplication", "Application")
                        .WithMany("ApplicationStatusHistories")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wnc.Models.AppUser", "ChangedByUser")
                        .WithMany("ApplicationStatusHistories")
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Application");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("wnc.Models.ApplicationSupplementRequest", b =>
                {
                    b.HasOne("wnc.Models.AdmissionApplication", "Application")
                        .WithMany("ApplicationSupplementRequests")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wnc.Models.AppUser", "RequestedByUser")
                        .WithMany("ApplicationSupplementRequests")
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("wnc.Models.AuditLog", b =>
                {
                    b.HasOne("wnc.Models.AppUser", "ActorUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("wnc.Models.AuthLog", b =>
                {
                    b.HasOne("wnc.Models.AppUser", "User")
                        .WithMany("AuthLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("wnc.Models.Candidate", b =>
                {
                    b.HasOne("wnc.Models.AppUser", "User")
                        .WithOne("Candidate")
                        .HasForeignKey("wnc.Models.Candidate", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("wnc.Models.CandidateEducationProfile", b =>
                {
                    b.HasOne("wnc.Models.Candidate", "Candidate")
                        .WithMany("EducationProfiles")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("wnc.Models.CandidatePriorityProfile", b =>
                {
                    b.HasOne("wnc.Models.Candidate", "Candidate")
                        .WithMany("PriorityProfiles")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("wnc.Models.EnrollmentConfirmation", b =>
                {
                    b.HasOne("wnc.Models.AdmissionApplication", "Application")
                        .WithOne("EnrollmentConfirmation")
                        .HasForeignKey("wnc.Models.EnrollmentConfirmation", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("wnc.Models.Major", b =>
                {
                    b.HasOne("wnc.Models.TrainingProgram", "Program")
                        .WithMany("Majors")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("wnc.Models.Notification", b =>
                {
                    b.HasOne("wnc.Models.AdmissionApplication", "Application")
                        .WithMany("Notifications")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("wnc.Models.NotificationTemplate", "Template")
                        .WithMany("Notifications")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("wnc.Models.AppUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("wnc.Models.PasswordResetToken", b =>
                {
                    b.HasOne("wnc.Models.AppUser", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("wnc.Models.RoundAdmissionMethod", b =>
                {
                    b.HasOne("wnc.Models.AdmissionMethod", "Method")
                        .WithMany("RoundAdmissionMethods")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("wnc.Models.RoundProgram", "RoundProgram")
                        .WithMany("RoundAdmissionMethods")
                        .HasForeignKey("RoundProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Method");

                    b.Navigation("RoundProgram");
                });

            modelBuilder.Entity("wnc.Models.RoundDocumentRequirement", b =>
                {
                    b.HasOne("wnc.Models.DocumentType", "DocumentType")
                        .WithMany("RoundDocumentRequirements")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("wnc.Models.RoundProgram", "RoundProgram")
                        .WithMany("RoundDocumentRequirements")
                        .HasForeignKey("RoundProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("RoundProgram");
                });

            modelBuilder.Entity("wnc.Models.RoundProgram", b =>
                {
                    b.HasOne("wnc.Models.Major", "Major")
                        .WithMany("RoundPrograms")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("wnc.Models.TrainingProgram", "Program")
                        .WithMany("RoundPrograms")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("wnc.Models.AdmissionRound", "Round")
                        .WithMany("RoundPrograms")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Major");

                    b.Navigation("Program");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("wnc.Models.SystemConfig", b =>
                {
                    b.HasOne("wnc.Models.AppUser", "UpdatedByUser")
                        .WithMany("UpdatedSystemConfigs")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("wnc.Models.UserRole", b =>
                {
                    b.HasOne("wnc.Models.AppUser", "AssignedByUser")
                        .WithMany("AssignedRoles")
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("wnc.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("wnc.Models.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("wnc.Models.AdmissionApplication", b =>
                {
                    b.Navigation("ApplicationDocuments");

                    b.Navigation("ApplicationPreferences");

                    b.Navigation("ApplicationReviewNotes");

                    b.Navigation("ApplicationStatusHistories");

                    b.Navigation("ApplicationSupplementRequests");

                    b.Navigation("EnrollmentConfirmation");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("wnc.Models.AdmissionMethod", b =>
                {
                    b.Navigation("ApplicationPreferences");

                    b.Navigation("RoundAdmissionMethods");
                });

            modelBuilder.Entity("wnc.Models.AdmissionRound", b =>
                {
                    b.Navigation("RoundPrograms");
                });

            modelBuilder.Entity("wnc.Models.AppUser", b =>
                {
                    b.Navigation("ApplicationReviewNotes");

                    b.Navigation("ApplicationStatusHistories");

                    b.Navigation("ApplicationSupplementRequests");

                    b.Navigation("AssignedRoles");

                    b.Navigation("AuditLogs");

                    b.Navigation("AuthLogs");

                    b.Navigation("Candidate");

                    b.Navigation("CreatedAdmissionRounds");

                    b.Navigation("Notifications");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("UpdatedSystemConfigs");

                    b.Navigation("UploadedDocuments");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("wnc.Models.Candidate", b =>
                {
                    b.Navigation("AdmissionApplications");

                    b.Navigation("EducationProfiles");

                    b.Navigation("PriorityProfiles");
                });

            modelBuilder.Entity("wnc.Models.DocumentType", b =>
                {
                    b.Navigation("ApplicationDocuments");

                    b.Navigation("RoundDocumentRequirements");
                });

            modelBuilder.Entity("wnc.Models.Major", b =>
                {
                    b.Navigation("ApplicationPreferences");

                    b.Navigation("RoundPrograms");
                });

            modelBuilder.Entity("wnc.Models.NotificationTemplate", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("wnc.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("wnc.Models.RoundProgram", b =>
                {
                    b.Navigation("AdmissionApplications");

                    b.Navigation("RoundAdmissionMethods");

                    b.Navigation("RoundDocumentRequirements");
                });

            modelBuilder.Entity("wnc.Models.TrainingProgram", b =>
                {
                    b.Navigation("ApplicationPreferences");

                    b.Navigation("Majors");

                    b.Navigation("RoundPrograms");
                });
#pragma warning restore 612, 618
        }
    }
}
